version: "3.5"
services:
    flask-api:
        container_name: "flask-api"
        build:
            context: ./api
        ports:
            - "5000:5000"
        environment: 
            - PYTHONPATH=/usr/src/app
